// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Among Us 1":return img`
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
...............fffffffff................
...............faaaaaacc................
.............ffaaaaaaaaaf...............
............faaaaaaaaaaacf..............
............faaaaaaaaaaaaf..............
............faaaaaaaaaaaacf.............
...........ffffffffaaaaaacf.............
..........ff1111199ffaaaaaf.............
..........f1199999996faaaaffff..........
..........f9999999966faaaafcaaf.........
..........ff66666666ffaaaafccaf.........
...........ffffffffffaaaaafccaf.........
...........faaaaaaaaaaaaaafccaf.........
...........faaaaaaaaaaaaaafccaf.........
...........faaaaaaaaaaaaaafcaaf.........
...........faaaaaaaaaaaaaafcaaf.........
...........faaaaaaaaaaaaacfcaaf.........
...........faaaaaaffaaaaacffff..........
...........faaaacf..faaaacf.............
...........faaaacf..faaaacf.............
...........faaaacf..faaaccf.............
...........faaaacf..faaaccf.............
...........faaaccf..fcccccf.............
............fffff....fffff..............
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
